/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuickEntryRouteImport } from './routes/quick-entry'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as MarriageIdRouteImport } from './routes/marriage.$id'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickEntryRoute = QuickEntryRouteImport.update({
  id: '/quick-entry',
  path: '/quick-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageIdRoute = MarriageIdRouteImport.update({
  id: '/marriage/$id',
  path: '/marriage/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/quick-entry': typeof QuickEntryRoute
  '/settings': typeof SettingsRoute
  '/tree': typeof TreeRoute
  '/marriage/$id': typeof MarriageIdRoute
  '/person/$id': typeof PersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/quick-entry': typeof QuickEntryRoute
  '/settings': typeof SettingsRoute
  '/tree': typeof TreeRoute
  '/marriage/$id': typeof MarriageIdRoute
  '/person/$id': typeof PersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/quick-entry': typeof QuickEntryRoute
  '/settings': typeof SettingsRoute
  '/tree': typeof TreeRoute
  '/marriage/$id': typeof MarriageIdRoute
  '/person/$id': typeof PersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/quick-entry'
    | '/settings'
    | '/tree'
    | '/marriage/$id'
    | '/person/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/quick-entry'
    | '/settings'
    | '/tree'
    | '/marriage/$id'
    | '/person/$id'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/quick-entry'
    | '/settings'
    | '/tree'
    | '/marriage/$id'
    | '/person/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  QuickEntryRoute: typeof QuickEntryRoute
  SettingsRoute: typeof SettingsRoute
  TreeRoute: typeof TreeRoute
  MarriageIdRoute: typeof MarriageIdRoute
  PersonIdRoute: typeof PersonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-entry': {
      id: '/quick-entry'
      path: '/quick-entry'
      fullPath: '/quick-entry'
      preLoaderRoute: typeof QuickEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage/$id': {
      id: '/marriage/$id'
      path: '/marriage/$id'
      fullPath: '/marriage/$id'
      preLoaderRoute: typeof MarriageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  QuickEntryRoute: QuickEntryRoute,
  SettingsRoute: SettingsRoute,
  TreeRoute: TreeRoute,
  MarriageIdRoute: MarriageIdRoute,
  PersonIdRoute: PersonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
